[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.variants_dir = variants
board_build.variant = aidrone_s3
monitor_speed = 115200
upload_speed = 921600
build_unflags = -DARDUINO_USB_MODE=1
build_flags =
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DCONFIG_TINYUSB_VENDOR_ENABLED=1
  -DCORE_DEBUG_LEVEL=1
